name: 🚀 CI - Test & Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install flask pytest

      - name: Run Pytest
        run: pytest

      - name: Build Docker Image
        run: docker build -t demo-app . 
