name: CD - Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Metadata
        run: |
          echo "COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE=pythoncodelife/auth-service:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "URL=https://auth-service-production-416b.up.railway.app/" >> $GITHUB_ENV

      - name: Deploy to Railway
        run: |
          curl -X POST "https://backboard.railway.app/project/${{ secrets.RAILWAY_ENVIRONMENT_ID_STAGING }}/service/${{ secrets.RAILWAY_SERVICE_ID_STAGING }}/deploy" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN_STAGING }}"

      - run: sleep 20

      - name: Health Check
        run: |
          RESPONSE=$(curl -s $URL)
          echo "RESPONSE=$RESPONSE" >> $GITHUB_ENV

      - name: Email Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME_STAGING }}
          password: ${{ secrets.MAIL_PASSWORD_DEV }}
          subject: "🚀 STAGING DEPLOY SUCCESS"
          to: ${{ secrets.MAIL_TO_STAGING }}
          cc: ${{ secrets.MAIL_CC_STAGING }}
          from: ${{ secrets.MAIL_USERNAME_STAGING }}
          body: |
            STAGING DEPLOY SUCCESS 🚀

            Commit: ${{ env.COMMIT }}
            Image: ${{ env.IMAGE }}

            URL:
            ${{ env.URL }}

            Response:
            ${{ env.RESPONSE }}
